---
name: Marie
surname: Curie
position: "Professor"
pronouns: she/her
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: +1 22 3333 4444
www: mariecurie.com
email: "Marie.Curie@ens.fr"
twitter: mariecurie
github: mariecurie
linkedin: mariecurie
date: "`r format(Sys.time(), '%B %Y')`"
output:
  vitae::awesomecv:
    page_total: true
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# install.packages("pacman")
pacman::p_load(rorcid,
               usethis,
               tidyverse,
               anytime,
               lubridate,
               janitor,
               vitae,
               rorcid,
               scholar,
               readxl)

# read files
readExcelSheets <- function(filename){
  # read all sheets in .xlsx 
  all <- readxl::excel_sheets(filename)
  # import each sheet into a list using readxl::read_excel
  list <- lapply(all, function(x) readxl::read_excel(filename, sheet = x))
  # save sheet name for each sheet (list)
  names(list) <- all
  # breaks up list and creates a dataframe for each sheet with df names matching sheet names
  list2env(list, envir = .GlobalEnv)
}

filename <- here::here("kenglish_vitae_data.xlsx")
readExcelSheets(filename)

```


# Scholarships

```{r scholarships}
# manual input from .xlsx
scholarships %>% 
  detailed_entries(what, when, with, where, why)
```

# Publications

```{r}
library(rorcid)
library(tidyverse)
out <- works(orcid_id("0000-0002-3050-2592")) 
 tibble(
   Journal = out$`journal-title.value`,
   Title = out$title.title.value,
   Year = out$`publication-date.year.value`,
   DOI = out$url.value
 ) %>% 
  detailed_entries(
  DOI,
  Journal,
  Title,
  Year
)
```
# Work experience

```{r}
my_exp <- do.call("bind_rows",
  rorcid::orcid_employments("0000-0002-3050-2592")$`0000-0002-3050-2592`$`affiliation-group`$summaries
)

#For the my_exp variable below: if there is no end date on your recent employment, replace `employment-summary.end-date.year.value` with `employment-summary.end-date`. 
my_exp %>%
  detailed_entries(
    what = `employment-summary.role-title`,
    when = glue::glue("{`employment-summary.start-date.year.value`} - {`employment-summary.end-date.year.value`}"),
    with = `employment-summary.organization.name`,
    where = glue::glue("{`employment-summary.organization.address.city`}, {`employment-summary.organization.address.region`}")
  )

```

